#!/bin/bash --login
#$ -cwd
#$ -N name
#$ -M harry.chown@postgrad.manchester.ac.uk
#$ -m e
#$ -pe smp.pe 32
#$ -l mem1500  
module load apps/binapps/anaconda3/2020.07
: <<'END'
conda activate emboss_env
transeq -sequence pan_genome_reference.fa -outseq pan_genome_peptides.fa

# SEARCH DB
# running a search in blastp mode
diamond blastp -d ~/scratch/imperial/ncbi-nr-refseq/reference -q pan_genome_peptides.fa -k 1 --max-hsps 1 -e 0.00001 --query-cover 50 --subject-cover 50 --id 70 -o staph.matches -p $NSLOTS

END

# FIND GENE IDS
conda activate diamondenv
awk '{ print $1 }' staph.matches > matched.centroids
awk '{ print $2 }' staph.matches > matched.peptides

for i in `cat matched.peptides`
do 
eresult=$(esearch -db protein -query ${i} | elink -target gene | esummary | xtract -pattern DocumentSummary -element Name)
echo "${i},${eresult}" >> matched.genes
done

# IF GENE ID'S CANNOT BE FOUND EXTRACT PROTEIN TITLE
cat matched.genes | grep ',$' > unmatched.genes
for i in `cat unmatched.genes`
do  
eresult=$(esearch -db protein -query ${i} | esummary | xtract -pattern DocumentSummary -element Title)
echo "${i},${eresult}" >> unmatched.fix.genes
done



